### ISSUE TITLE
Error on PUT 

### ISSUE THREAD

**Issue by joebalancio** [mio/express#5]
```
/mnt/BC/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:245
        throw message;
              ^
TypeError: Cannot read property 'constructor' of null
    at prepareResource (/mnt/models/node_modules/mio-mongo/lib/mio-mongo.js:1030:27)
    at Function.prepareResource (/mnt/models/node_modules/mio-mongo/lib/mio-mongo.js:1039:9)
    at Function.Resource.emit (/mnt/models/node_modules/mio/lib/resource.js:948:20)
    at resource.Resource.set (/mnt/models/node_modules/mio/lib/resource.js:1274:22)
    at Function.<anonymous> (/mnt/models/node_modules/mio-express/lib/mio-express.js:294:14)
    at done (/mnt/models/node_modules/mio/lib/resource.js:1091:14)
    at next (/mnt/models/node_modules/mio/lib/resource.js:1062:12)
    at /mnt/models/node_modules/mio-mongo/lib/mio-mongo.js:314:9
    at /mnt/BC/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection/query.js:159:5
    at Cursor.nextObject (/mnt/BC/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:742:5)
```

**Comment by alexmingoia** [comment]
This is actually an error with `mio-mongo` and should be fixed in `mio-mongo@0.9.4`.
